name: Build and Deploy LaTeX HTML

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: texlive/texlive:latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up LaTeX environment
        run: |
          apt update && apt upgrade -y

      - name: Install nodejs
        run: |


      - name: Build HTML from LaTeX
        run: |
          make4ht -c html.cfg -d html main.tex && mv html/main.html html/index.html

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: html
          path: html/

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: html
          path: html/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./html
          target_branch: gh-pages
